fix(Web): Remove parent view with flex:1
expo/react-native-appearance pull request #36
Opened 2020-02-04 12:11 UTC by darmawanalbert

Currently, `NativeAppearanceProvider` for web returns `View` with `flex:1`. When I add `AppearanceProvider` at my app root, the layout changes:
![Screen Shot 2020-02-04 at 19 01 25](https://user-images.githubusercontent.com/12585587/73743598-853de200-4781-11ea-83c1-499285fb5667.png)
 
However, if I clone `props.children` instead, the layout goes back to normal: 
![Screen Shot 2020-02-04 at 19 02 39](https://user-images.githubusercontent.com/12585587/73743636-9f77c000-4781-11ea-9ff9-e8c9aa2ec433.png)

Having said that, do you have any specific reason on why you return `View` with `flex:1`? Please kindly advise, as I am not sure if my proposed solution is legit 🙇

2020-02-04 22:06 UTC, EvanBacon commented
I do it for parity with [Android shim](https://github.com/expo/react-native-appearance/blob/91717e9ceab753b6a2fa779d4fd37696b0061a4c/src/NativeAppearance.tsx#L4). CC @brentvatne

2020-02-04 22:07 UTC, EvanBacon requested changes
Android uses a `View` with `flex: 1`. If we change it here, we should change it there too https://github.com/expo/react-native-appearance/blob/91717e9ceab753b6a2fa779d4fd37696b0061a4c/src/NativeAppearance.tsx#L4

2020-02-04 22:54 UTC, brentvatne commented
any idea why this causes the padding issues you observed?

2020-02-06 08:56 UTC, darmawanalbert commented
@brentvatne still investigating the root cause. I will try to simulate this on empty project and will let you know if I find anything 🙇

2020-03-19 10:17 UTC, darmawanalbert commented
I couldn't find a solid justification for this PR, therefore I will close this PR 🙇

2020-03-19 10:17 UTC, closed without merging